'use client'

import Head from 'next/head'
import { DefaultTheme, ThemeProvider } from 'styled-components'
import GlobalStyle from '../styles/GlobalStyle'

const theme: DefaultTheme = {
  colors: {
    primary: '#111',
    secondary: '#0070f3',
  },
}

export default function Home() {
  return (
    <ThemeProvider theme={theme}>
      <GlobalStyle />
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
    </ThemeProvider>
  )
}
